FROM node:10.16.0

RUN mkdir -p /src/app

RUN apt-get -q update && apt-get -qy install netcat
RUN npm i npm@latest -g

WORKDIR /src
COPY package.json package-lock.json* ./
RUN npm install && npm cache clean --force
ENV PATH /src/node_modules/.bin:$PATH

WORKDIR /src/app
COPY . /src/app

CMD ["npm", "run", "start"]

